### ISSUE TITLE
More types of DGA-generated domain are needed(optional)

### ISSUE THREAD

**Issue by Tristan-Chow** [Tristan-Chow/Malicious-and-Benign-domain-detection#1]
Now we only have types of banjori and chinad, for generalization purpose, it is better to run all dga algorithms and generate different kinds of domain names.

**Comment by Tristan-Chow** [comment]
may use source node in this link https://github.com/endgameinc/dga_predict/tree/708485867f9070316167f23ca0c581c69a481d1f

**Comment by Yvonne61m** [comment]
Got more dga data. Expanded the dataset to 60,000 domains. (half dga)
