### ISSUE TITLE
Check how to integrate NLTK and tldextract in AWS lambda

### ISSUE THREAD

**Issue by Tristan-Chow** [Tristan-Chow/Malicious-and-Benign-domain-detection#6]
https://medium.com/datadriveninvestor/how-to-set-up-layers-python-in-aws-lambda-functions-1355519c11ed
This link should work, also if it works, please generate the compressed zip file and upload to our repo.

**Comment by Yvonne61m** [comment]
I followed the instruction and the same OS (Ubuntu 18.04) and uploaded the zip file. However, it looks a bit different than the instruction. Please let me know if it works or not. I don't have the permission to add it to the layer and test it for now.

**Comment by Yvonne61m** [comment]
Upload the new nltk package. Tested on my AWS lambda function. This should work.

**Comment by Tristan-Chow** [comment]
successfully adding layers, close this issue
